groups:
- name: node-exporter
  rules:
  - alert: NodeFilesystemSpaceFillingUp
    annotations:
      description: Filesystem on {{ $labels.device }} at {{ $labels.instance }} has
        only {{ printf "%.2f" $value }}% available space left and is filling up.
      runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-nodefilesystemspacefillingup
      summary: Filesystem is predicted to run out of space within the next 24 hours.
    expr: |-
      (
        node_filesystem_avail_bytes{job=~".*node-exporter.*|.*node_exporter.*",fstype!=""} / node_filesystem_size_bytes{job=~".*node-exporter.*|.*node_exporter.*",fstype!=""} * 100 < 40
      and
        predict_linear(node_filesystem_avail_bytes{job=~".*node-exporter.*|.*node_exporter.*",fstype!=""}[6h], 24*60*60) < 0
      and
        node_filesystem_readonly{job=~".*node-exporter.*|.*node_exporter.*",fstype!=""} == 0
      )
    for: 1h
    labels:
      severity: warning
  - alert: NodeFilesystemSpaceFillingUp
    annotations:
      description: Filesystem on {{ $labels.device }} at {{ $labels.instance }} has
        only {{ printf "%.2f" $value }}% available space left and is filling up fast.
      runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-nodefilesystemspacefillingup
      summary: Filesystem is predicted to run out of space within the next 4 hours.
    expr: |-
      (
        node_filesystem_avail_bytes{job=~".*node-exporter.*|.*node_exporter.*",fstype!=""} / node_filesystem_size_bytes{job=~".*node-exporter.*|.*node_exporter.*",fstype!=""} * 100 < 15
      and
        predict_linear(node_filesystem_avail_bytes{job=~".*node-exporter.*|.*node_exporter.*",fstype!=""}[6h], 4*60*60) < 0
      and
        node_filesystem_readonly{job=~".*node-exporter.*|.*node_exporter.*",fstype!=""} == 0
      )
    for: 1h
    labels:
      severity: critical
  - alert: NodeFilesystemAlmostOutOfSpace
    annotations:
      description: Filesystem on {{ $labels.device }} at {{ $labels.instance }} has
        only {{ printf "%.2f" $value }}% available space left.
      runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-nodefilesystemalmostoutofspace
      summary: Filesystem has less than 5% space left.
    expr: |-
      (
        node_filesystem_avail_bytes{job=~".*node-exporter.*|.*node_exporter.*",fstype!=""} / node_filesystem_size_bytes{job=~".*node-exporter.*|.*node_exporter.*",fstype!=""} * 100 < 5
      and
        node_filesystem_readonly{job=~".*node-exporter.*|.*node_exporter.*",fstype!=""} == 0
      )
    for: 1h
    labels:
      severity: warning
  - alert: NodeFilesystemAlmostOutOfSpace
    annotations:
      description: Filesystem on {{ $labels.device }} at {{ $labels.instance }} has
        only {{ printf "%.2f" $value }}% available space left.
      runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-nodefilesystemalmostoutofspace
      summary: Filesystem has less than 3% space left.
    expr: |-
      (
        node_filesystem_avail_bytes{job=~".*node-exporter.*|.*node_exporter.*",fstype!=""} / node_filesystem_size_bytes{job=~".*node-exporter.*|.*node_exporter.*",fstype!=""} * 100 < 3
      and
        node_filesystem_readonly{job=~".*node-exporter.*|.*node_exporter.*",fstype!=""} == 0
      )
    for: 1h
    labels:
      severity: critical
  - alert: NodeFilesystemFilesFillingUp
    annotations:
      description: Filesystem on {{ $labels.device }} at {{ $labels.instance }} has
        only {{ printf "%.2f" $value }}% available inodes left and is filling up.
      runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-nodefilesystemfilesfillingup
      summary: Filesystem is predicted to run out of inodes within the next 24 hours.
    expr: |-
      (
        node_filesystem_files_free{job=~".*node-exporter.*|.*node_exporter.*",fstype!=""} / node_filesystem_files{job=~".*node-exporter.*|.*node_exporter.*",fstype!=""} * 100 < 40
      and
        predict_linear(node_filesystem_files_free{job=~".*node-exporter.*|.*node_exporter.*",fstype!=""}[6h], 24*60*60) < 0
      and
        node_filesystem_readonly{job=~".*node-exporter.*|.*node_exporter.*",fstype!=""} == 0
      )
    for: 1h
    labels:
      severity: warning
  - alert: NodeFilesystemFilesFillingUp
    annotations:
      description: Filesystem on {{ $labels.device }} at {{ $labels.instance }} has
        only {{ printf "%.2f" $value }}% available inodes left and is filling up fast.
      runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-nodefilesystemfilesfillingup
      summary: Filesystem is predicted to run out of inodes within the next 4 hours.
    expr: |-
      (
        node_filesystem_files_free{job=~".*node-exporter.*|.*node_exporter.*",fstype!=""} / node_filesystem_files{job=~".*node-exporter.*|.*node_exporter.*",fstype!=""} * 100 < 20
      and
        predict_linear(node_filesystem_files_free{job=~".*node-exporter.*|.*node_exporter.*",fstype!=""}[6h], 4*60*60) < 0
      and
        node_filesystem_readonly{job=~".*node-exporter.*|.*node_exporter.*",fstype!=""} == 0
      )
    for: 1h
    labels:
      severity: critical
  - alert: NodeFilesystemAlmostOutOfFiles
    annotations:
      description: Filesystem on {{ $labels.device }} at {{ $labels.instance }} has
        only {{ printf "%.2f" $value }}% available inodes left.
      runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-nodefilesystemalmostoutoffiles
      summary: Filesystem has less than 5% inodes left.
    expr: |-
      (
        node_filesystem_files_free{job=~".*node-exporter.*|.*node_exporter.*",fstype!=""} / node_filesystem_files{job=~".*node-exporter.*|.*node_exporter.*",fstype!=""} * 100 < 5
      and
        node_filesystem_readonly{job=~".*node-exporter.*|.*node_exporter.*",fstype!=""} == 0
      )
    for: 1h
    labels:
      severity: warning
  - alert: NodeFilesystemAlmostOutOfFiles
    annotations:
      description: Filesystem on {{ $labels.device }} at {{ $labels.instance }} has
        only {{ printf "%.2f" $value }}% available inodes left.
      runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-nodefilesystemalmostoutoffiles
      summary: Filesystem has less than 3% inodes left.
    expr: |-
      (
        node_filesystem_files_free{job=~".*node-exporter.*|.*node_exporter.*",fstype!=""} / node_filesystem_files{job=~".*node-exporter.*|.*node_exporter.*",fstype!=""} * 100 < 3
      and
        node_filesystem_readonly{job=~".*node-exporter.*|.*node_exporter.*",fstype!=""} == 0
      )
    for: 1h
    labels:
      severity: critical
  - alert: NodeHighNumberConntrackEntriesUsed
    annotations:
      description: '{{ $value | humanizePercentage }} of conntrack entries are used.'
      runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-nodehighnumberconntrackentriesused
      summary: Number of conntrack are getting close to the limit.
    expr: (node_nf_conntrack_entries / node_nf_conntrack_entries_limit) > 0.75
    labels:
      severity: warning
  - alert: NodeTextFileCollectorScrapeError
    annotations:
      description: Node Exporter text file collector failed to scrape.
      runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-nodetextfilecollectorscrapeerror
      summary: Node Exporter text file collector failed to scrape.
    expr: node_textfile_scrape_error{job=~".*node-exporter.*|.*node_exporter.*"} == 1
    labels:
      severity: warning
  - alert: NodeRAIDDegraded
    annotations:
      description: RAID array '{{ $labels.device }}' on {{ $labels.instance }} is
        in degraded state due to one or more disks failures. Number of spare drives
        is insufficient to fix issue automatically.
      runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-noderaiddegraded
      summary: RAID Array is degraded
    expr: node_md_disks_required - ignoring (state) (node_md_disks{state="active"})
      > 0
    for: 15m
    labels:
      severity: critical
  - alert: NodeRAIDDiskFailure
    annotations:
      description: At least one device in RAID array on {{ $labels.instance }} failed.
        Array '{{ $labels.device }}' needs attention and possibly a disk swap.
      runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-noderaiddiskfailure
      summary: Failed device in RAID array
    expr: node_md_disks{state="failed"} > 0
    labels:
      severity: warning
  - alert: NodeFileDescriptorLimit
    annotations:
      description: File descriptors limit at {{ $labels.instance }} is currently at
        {{ printf "%.2f" $value }}%.
      runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-nodefiledescriptorlimit
      summary: Kernel is predicted to exhaust file descriptors limit soon.
    expr: |-
      (
        node_filefd_allocated{job=~".*node-exporter.*|.*node_exporter.*"} * 100 / node_filefd_maximum{job=~".*node-exporter.*|.*node_exporter.*"} > 70
      )
    for: 15m
    labels:
      severity: warning
  - alert: NodeFileDescriptorLimit
    annotations:
      description: File descriptors limit at {{ $labels.instance }} is currently at
        {{ printf "%.2f" $value }}%.
      runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-nodefiledescriptorlimit
      summary: Kernel is predicted to exhaust file descriptors limit soon.
    expr: |-
      (
        node_filefd_allocated{job=~".*node-exporter.*|.*node_exporter.*"} * 100 / node_filefd_maximum{job=~".*node-exporter.*|.*node_exporter.*"} > 90
      )
    for: 15m
    labels:
      severity: critical
  - alert: Node down
    expr: up == 0
    for: 3m
    labels:
      severity: critical
    annotations:
      title: Node {{ $labels.instance }} is down
      description: Failed to scrape {{ $labels.job }} on {{ $labels.instance }} for more than 3 minutes. Node seems to be down.
  - alert: NodeHasRebooted
    annotations:
      description: Node has rebooted in last 10 minutes
      summary: Node {{ (or $labels.node $labels.instance) }} has rebooted {{ $value }} seconds ago.
    expr: |
            (time() - node_boot_time_seconds < 600) and (time() - 600 - (node_boot_time_seconds offset 10m) > 600)
    labels:
      severity: critical
