#add needed packages
- name: Install packages
  apt:
    name: "{{ packages }}"
    state: present

- name: Add an apt grafana signing key
  ansible.builtin.apt_key:
    url: https://apt.grafana.com/gpg.key
    state: present
    keyring: /usr/share/keyrings/grafana.key
  when: ansible_os_family == "Debian"

- name: Register debian destribution
  shell: lsb_release -cs
  register: lsb_release
  when: ansible_os_family == "Debian"

- name: Register debian arhitecture
  shell: dpkg --print-architecture
  register: arch
  when: ansible_os_family == "Debian"


- name: Add repository for grafana
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/grafana.key] https://apt.grafana.com stable main"
    state: present

#Install the latest Grafana Enterprise release:
- name: Install grafana latest
  apt:
    name:
      - grafana-enterprise=9.4.3
    state:  present
    update_cache: yes

- name: "Grafana configuration file copy"
  template:
    src: "grafana.conf.j2"
    dest: /etc/grafana/grafana.ini
  notify: event_restart_grafana

- name: "Grafana server started"
  service:
    name: grafana-server
    enabled: true
    state: started

- name: "Check if Grafana is accessible"
  uri:
    url: http://{{hostvars[item].ansible_host}}:3000
    method: GET
    status_code: 200
  with_items: 
    - "{{ groups.grafana }}"
