---
- hosts: alertmanager
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - alertmanager
  tags: [ 'never', 'alertmanager' ]

- hosts: node_exporter
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - prometheus_node_exporter
  tags: [ 'never', 'prometheus_node_exporter' ]

- hosts: prometheus
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - prometheus
  tags: [ 'never', 'prometheus' ]

- hosts: grafana
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - grafana
  tags: [ 'never', 'grafana' ]