groups:
- name: swarm_node.rules.yml
  rules:
  - alert: node_cpu_usage
    expr: 100 - (avg(irate(node_cpu_seconds_total{mode="idle"}[1m]) * ON(instance) GROUP_LEFT(node_name)
      node_meta * 100) BY (node_name)) > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      description: Swarm node {{ $labels.node_name }} CPU usage is at {{ humanize
        $value}}%.
      summary: CPU alert for Swarm node '{{ $labels.node_name }}'
  - alert: node_memory_usage
    expr: sum(((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes)
      * ON(instance) GROUP_LEFT(node_name) node_meta * 100) BY (node_name) > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      description: Swarm node {{ $labels.node_name }} memory usage is at {{ humanize
        $value}}%.
      summary: Memory alert for Swarm node '{{ $labels.node_name }}'
  - alert: node_disk_usage for /
    expr: ((node_filesystem_size_bytes{mountpoint="/"} - node_filesystem_free_bytes{mountpoint="/"})
      * 100 / node_filesystem_size_bytes{mountpoint="/"}) * ON(instance) GROUP_LEFT(node_name)
      node_meta > 85
    for: 5m
    labels:
      severity: warning
    annotations:
      description: Swarm node {{ $labels.node_name }} disk usage for / is at {{ humanize
        $value}}%.
      summary: Disk alert for / for Swarm node '{{ $labels.node_name }}'
  - alert: node_disk_fill_rate_6h for /
    expr: predict_linear(node_filesystem_free_bytes{mountpoint="/"}[1h], 6 * 3600) * ON(instance)
      GROUP_LEFT(node_name) node_meta < 0
    for: 1h
    labels:
      severity: critical
    annotations:
      description: Swarm node {{ $labels.node_name }} disk on / is going to fill up in
        6h.
      summary: Disk fill alert on / for Swarm node '{{ $labels.node_name }}'
  - alert: node_disk_usage for var/containers
    expr: ((node_filesystem_size_bytes{mountpoint="/var/containers"} - node_filesystem_free_bytes{mountpoint="/var/containers"})
      * 100 / node_filesystem_size_bytes{mountpoint="/var/containers"}) * ON(instance) GROUP_LEFT(node_name)
      node_meta > 85
    for: 1m
    labels:
      severity: warning
    annotations:
      description: Swarm node {{ $labels.node_name }} disk usage for /var/containers  is at {{ humanize
        $value}}%.
      summary: Disk alert /var/containers  for Swarm node '{{ $labels.node_name }}' 
  - alert: node_disk_fill_rate_6h for /var/containers
    expr: predict_linear(node_filesystem_free_bytes{mountpoint="/var/containers"}[1h], 6 * 3600) * ON(instance)
      GROUP_LEFT(node_name) node_meta < 0
    for: 1h
    labels:
      severity: critical
    annotations:
      description: Swarm node {{ $labels.node_name }} disk on /var/containers is going to fill up in
        6h.
      summary: Disk fill alert on /var/containers for Swarm node '{{ $labels.node_name }}'
